# Generated by Django 5.0.2 on 2024-03-05 22:36

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('quote', wagtail.blocks.BlockQuoteBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(required=False)), ('code_snippet', wagtail.blocks.TextBlock(form_classname='Code Snippet', required=False))]),
        ),
    ]
