# Generated by Django 5.0.2 on 2024-03-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cloudinary_image', '0001_initial'),
        ('blog', '0011_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagegallery',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_cloudinary_image.cloudinaryimage'),
        ),
    ]